### ISSUE TITLE
Error: ENOENT: no such file or directory, open..

### ISSUE THREAD

**Issue by spenncerr** [brob/eleventy-plugin-svg-contents#10]
Hey Bryan,

I'm getting the following error when attempting to use this SVG plugin with Nunjucks:

`> Having trouble rendering njk template ./src/index.njk

TemplateContentRenderError was thrown
> (./src/index.njk)
  Template render error: (/Users/spencer/Local/samcat/src/_includes/partials/components/servicesList.njk)
  Error: ENOENT: no such file or directory, open './images/service1.svg'

Template render error was thrown:
    Template render error: (./src/index.njk)
      Template render error: (/Users/spencer/Local/samcat/src/_includes/partials/components/servicesList.njk)
      Error: ENOENT: no such file or directory, open './images/service1.svg'
        at Object._prettifyError (/Users/spencer/Local/samcat/node_modules/nunjucks/src/lib.js:36:11)
        at /Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:561:19
        at eval (eval at _compile (/Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:60:12)
        at /Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:569:11
        at Template.root [as rootRenderFunc] (eval at _compile (/Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:52:3)
        at Template.render (/Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:550:10)
        at eval (eval at _compile (/Users/spencer/Local/samcat/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:59:10)
        at fn (/Users/spencer/Local/samcat/node_modules/a-sync-waterfall/index.js:26:24)
        at /Users/spencer/Local/samcat/node_modules/a-sync-waterfall/index.js:66:22
        at executeSync (/Users/spencer/Local/samcat/node_modules/a-sync-waterfall/index.js:8:15)
Copied 1 item and Processed 0 files in 0.06 seconds (v0.9.0)`

Any idea why?

**Comment by brob** [comment]
Hey @spenncerr, any chance you've got a link to a repo for the site?

**Comment by spenncerr** [comment]
Hey @brob, I don't unfortunately. Is there anything you need me to share with you to problem-solve the error?

**Comment by brob** [comment]
Basically, I'd just love to see more details about your project structure. The two things I think it could be are the SVG path is off a little or there's an issue with using the filter in an include. 

Also, the plugin assumes that the path you give it is the root of your project not necessarily where the various source files live, so if your images folder are in another spot (say a src directory, or something similar) it could cause issues. I need to make that a bit more resilient, to be honest... If your images ARE in your src directory, the easy fix would be to pass the filter the path prepended with `/src/`

I've tested an include locally and it seems to be working so more information on the project structure would help me figure out where things are going wrong.

**Comment by spenncerr** [comment]
Hi @brob 

I think you hit the nail on the head with the `/src/` stuff as my whole project is within that directory. I'll give that a go now.

Thanks!

**Comment by spenncerr** [comment]
Solved! I was grabbing the SVG path from a `_data/services.json` file. But as I wasn't including the `/src/` in that path it wasn't working. Adding that has fixed it.

Thanks @brob !
